### ISSUE TITLE
Battery Drain

### ISSUE THREAD

**Issue by NKentatE** [Gedsh/InviZible#139]
I am connected invizible pro with dnscrypt only.
When invizible pro connected more battery drain compare to other like personal dns filter.
Nearly 50 percent battery 

> eat by invizible pro.

**Comment by NKentatE** [comment]
It eat more battery when network disconnected and invizible pro connected.

When i see realtime log at network disconnected it search every second for network.
Is it possible to stop search until network connected?

**Comment by Gedsh** [comment]
> I am connected invizible pro with dnscrypt only.

DNSCrypt itself consumes a bit of battery. Tor consumes more power. I2P has high consumption since it is a P2P app.
If your device shows a high level of consumption with DNSCrypt, this usually means an incorrect calculation due to the foreground service (notification in the status bar). Or foreground service is preventing your device from sleeping. It depends on your rom. In any case, I can not do anything about it.

> When invizible pro connected more battery drain compare to other like personal dns filter.

InviZible intercepts all device traffic using a local VPN and redirects it to DNSCrypt, Tor and I2P networks. If you are only using DNSCrypt, InviZible will only forward DNS requests. Other traffic goes directly to the destination. But in any case, InviZible handles all device traffic, unlike a personal DNS filter. Because of this, android thinks that InviZible is generating this traffic and should have a high power consumption. But InviZible doesn't generate traffic, it only redirects it. This is usually the cause of incorrect calculation.

> When i see realtime log at network disconnected it search every second for network.

What application is searching for the network? InviZible itself does not do this.

**Comment by NKentatE** [comment]
Unlike pesonal dns filter, invizible pro with dnscrypt client (dns server) choose multiple server and then start service it choose lowest ms..from the time after 4 hours it automatically choose with lowest ms..
But when internet connect is disconnected(after 4 hours) until connect it will try and try to connect.

Unlike personal dns filter will will choose lowest ms immediately and when internet disconnect it will not trying to connect.
If internet connected it will connect and start working.

**Comment by Gedsh** [comment]
> But when internet connect is disconnected(after 4 hours) until connect it will try and try to connect

This is the reaction when your phone applications send DNS queries. If you think this behavior is wrong, please contact the DNSCrypt developer. InviZible uses the original DNSCrypt binary from the DNSCrypt project: https://github.com/DNSCrypt/dnscrypt-proxy

> Unlike personal dns filter

Why not use a personal DNS filter if you like its behavior? This is a good open source project.

Regarding DNSCrypt behavior and battery drain. InviZible consumes 2-3% per day on my phone with DNSCrypt only enabled.

**Comment by NKentatE** [comment]
>

**Comment by NKentatE** [comment]
> Why not use a personal DNS filter if you like its behavior? This is a good open source project.

Because it does not support dnscrypt

**Comment by NKentatE** [comment]
> Regarding DNSCrypt behavior and battery drain. InviZible consumes 2-3% per day on my phone with DNSCrypt only enabled.

When active invizible pro in night time it reduce battery nearly 40 percent

When disconnected that day only reduce upto 10 percent

**Comment by Gedsh** [comment]
> Because it does not support dnscrypt

Therefore, if you need DNSCrypt, you should contact the DNSCrypt developer with your suggestion.

> When active invizible pro in night time it reduce battery nearly 40 percent

I use DNSCrypt 24/7 and the battery consumption is 2-3% I also turn off the internet at night. So I don't have your problem.

Perhaps the problem is not in DNSCrypt, but in the android incorrect calculation as mentioned above.

**Comment by NKentatE** [comment]
Okay i will check it out.
Until week before there is no problem.
Few days have this issue.

**Comment by Gedsh** [comment]
> Few days have this issue.

The last DNSCrypt update was 7 months ago.

InviZible itself also has no battery consumption changes for several versions.

**Comment by NKentatE** [comment]
Okay

**Comment by NKentatE** [comment]
Open Discussion in Dnscypt Proxy.
Waiting for Reply.
If I found anything, i will reopen the issue.
Thanks for fast reply and wonderful app.

**Comment by NKentatE** [comment]
By any chance battery drain because of blacklist (ad blocker hosts) and i am using many hosts to block ads in invizible.

**Comment by Gedsh** [comment]
> By any chance battery drain because of blacklist (ad blocker hosts) and i am using many hosts to block ads in invizible.

A huge blacklist of more than a few MB can significantly increase battery consumption.

> Thanks for fast reply and wonderful app.

You are welcome.

**Comment by NKentatE** [comment]
> A huge blacklist of more than a few MB can significantly increase battery consumption.

I have nearly 60 mb of blocklist.

**Comment by Gedsh** [comment]
> nearly 60 mb

It's too much. This does not affect performance, but it does affect battery consumption. I recommend using a blocklist of no more than 10 MB.

**Comment by NKentatE** [comment]
> It's too much. This does not affect performance, but it does affect battery consumption

Oh ok ok

> I recommend using a blocklist of no more than 10 MB

Thanks i will reduce the blocklist size.
