### ISSUE TITLE
Add ODOH support

### ISSUE THREAD

**Issue by awebeer256** [Gedsh/InviZible#142]
I added the lists of ODOH servers and relays from [dnscrypt-resolvers](https://github.com/DNSCrypt/dnscrypt-resolvers), but when I went to pick servers, they didn't show up. ODOH support was added to dnscrypt-proxy in version 2.1.0, and InviZible uses version 2.1.1, so I expect I could use it by editing `dnscrypt-proxy.toml` manually, but of course that's a *horrendous* UX! 😋

Please add ODOH support to the GUI.

I'm using the latest F-Droid beta version of InviZible (1.6.3).

**Comment by Gedsh** [comment]
> I added the lists of ODOH servers and relays from [dnscrypt-resolvers](https://github.com/DNSCrypt/dnscrypt-resolvers), but when I went to pick servers, they didn't show up.

InviZible will not read this file as it needs to be added to the source code..

> I expect I could use it by editing dnscrypt-proxy.toml manually

You can do this because InviZible uses the original DNSCrypt. But you should complete all configuration steps without using the user interface.

> Please add ODOH support to the GUI.

I am planning to add this feature. But currently there are only 12 ODOH servers. So it's not much of a choice.

**Comment by e-t-l** [comment]
> I could use it by editing dnscrypt-proxy.toml manually

@awebeer256 Did you end up doing this? If so, what edits were required to get ODOH working?

**Comment by Gedsh** [comment]
Fixed via 2f3a150884067932c29636c290f8f082407a0278
