### ISSUE TITLE
How does ARP poising detection works ?

### ISSUE THREAD

**Issue by Rexadev** [Gedsh/InviZible#240]
and where to see it's logs to check how did the attack and what was the attack ?

Or if it is just a flase positive.

**Comment by Gedsh** [comment]
InviZible checks the IP and Mac addresses of the default gateway. If they change while InviZible is running, this could be an attack. But it could also be a false positive if you have multiple Wi-Fi access points on your home network. No additional information is provided because InviZible is unable to determine the reason for the change.
