### ISSUE TITLE
OS DNS is not working when disabling DNSCrypt

### ISSUE THREAD

**Issue by derjohn** [Gedsh/InviZible#252]
Hello,
If I disable dnscrypt I can't get the OS default DNS working. I tried reconnecting got get new DHCP  etc ...but vanadium only get's "cannot resolve xyz".

Best Regards,
j

**Comment by Gedsh** [comment]
Hello,

I don't know what mode you are using, Root or VPN, but either way a restart will remove all effects. If restarting doesn't help, the problem is not in InviZIble.

**Comment by derjohn** [comment]
Oh,
I am using VPN mode on GrapheneOS (so: non root). If I disable and/or stop Invizible , I get DNS query errors in the apps. I also rebooted with stopped DNScrypt, but the issue remains until I start DNSCrypt again.

**Comment by Gedsh** [comment]
> I also rebooted with stopped DNScrypt

Perhaps you have activated Always On VPN in your phone settings..?

Try uninstalling the app and rebooting again. You will know for sure that the problem is not with InviZible.

But I'm sure the problem is in your rom. InviZible doesn't do anything special, it just activates a local VPN which can't harm your phone in any way.
