### ISSUE TITLE
Cannot start proxy without selecting app to exclude, but cannot use app in work profile 

### ISSUE THREAD

**Issue by mvevitsis** [Gedsh/InviZible#274]
The app requires you to select at least one app to exclude to start the proxy, however if the proxy server is installed in a work profile, you cannot select it.

![Screenshot_20240728-121630_InviZible Pro.png](https://github.com/user-attachments/assets/334319df-4d3b-4dd9-9803-bd19cf8fbccf)

![Screenshot_20240728-121720_InviZible Pro.png](https://github.com/user-attachments/assets/80512500-5ccd-4b8c-9fa7-aecf16c0bf6d)

**Comment by Gedsh** [comment]
InviZible needs root to be able to see and manage apps in the work profile. 

This is a simple protection. You can just exclude any innocent app. I don't want to completely disable this protection, because it is very common that a user forgets to select a proxy app and creates a loop. And your case is very rare.
