### ISSUE TITLE
Option to manage Captive portal 

### ISSUE THREAD

**Issue by shuvashish76** [Gedsh/InviZible#288]
Changing the captive portal servers is a privacy benefit and no root privileges needed.
There are presets from [GrapheneOS](https://grapheneos.org/faq#default-connections), [Kuketz](https://www.kuketz-blog.de/empfehlungsecke/#captive-portal) and the defaults of Google.
It goes in the sprit of InviZible privacy specific feature list.

Reference :
- https://f-droid.org/packages/io.github.muntashirakon.captiveportalcontroller/
- https://mullvad.net/en/blog/2022/10/10/android-leaks-connectivity-check-traffic

**Comment by Gedsh** [comment]
As you mentioned, there is already another app for this purpose, small and simple. You can even delete that app after changing the captive portal.

On the other hand, this option requires the dangerous android.permission.WRITE_SECURE_SETTINGS permission, which would look suspicious in an app like InviZible.

**Comment by shuvashish76** [comment]
I thought no harm in supporting this this feature since InviZible has already root support.

**Comment by Gedsh** [comment]
> InviZible has already root support

But InviZible doesn't have the necessary permission, which is still required when using root.

**Comment by M1ssing-N0** [comment]
I think @shuvashish76 meant the captive-portals.txt which is a feature of dnscrypt-proxy rather than the global setting of android system. It's similar to how cloaking rules and forwarding rules work in dnscrypt-proxy.
The content of this file is only managed by inviZible for users without root access so having the setting to modify its content can be pretty helpful.

Reference: https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Captive-Portals
