### ISSUE TITLE
Premium Lite and Pro versions

### ISSUE THREAD

**Issue by grm34** [Gedsh/InviZible#293]
I just realized that :

- the versions offered on the PlayStore and in direct APK here on github are Lite versions with a popup every 30 seconds reminding you to pay for a Pro version [here](https://invizible.net/en/donate/).

- the version offered on F-Droid is a free Pro version.

I'm tempted to say good for F-Droid users, but from the point of view of those who have paid for the same thing, it seems a little disturbing.

**Comment by Gedsh** [comment]
> I just realized that

You can support the project or not. You can use the paid version or the free version. Either way, you will have access to all the features to improve your privacy and anonymity. It's all about choice and therefore freedom.

> I'm tempted to say good for F-Droid users, but from the point of view of those who have paid for the same thing, it seems a little disturbing.

Most people who purchase the app do so just to support the project, and then use whatever version they want. They want it to evolve, to improve. There is nothing secret about the availability of other versions. Try using any search engine or github releases or whatever. But the problem is people who only want to consume and provide nothing.

**Comment by Gedsh** [comment]
There seems to be nothing to add here.
