### ISSUE TITLE
Tor bootstrap stops at 5% and doesn't connect (Beta&Prod)

### ISSUE THREAD

**Issue by TheWiFiNerds** [Gedsh/InviZible#305]
I think the beta was posted to fix this, but I also have an issue with the beta now.

**Comment by Gedsh** [comment]
This means you are using the wrong configuration or Tor is blocked by your ISP.

So you should first reset InviZible settings to defaults, and if your ISP may be blocking Tor, you should read about [Tor bridges](https://github.com/Gedsh/InviZible/wiki/Tor-Bridges), which are designed to circumvent censorship.

In any case, this is not an issue with InviZible or Tor itself and cannot simply be fixed in any version. If your ISP has started blocking Tor, you need to learn how to bypass this blocking. This is possible with Tor and InviZible.
