### ISSUE TITLE
Start Stop in notification 

### ISSUE THREAD

**Issue by timea-techgirl** [Gedsh/InviZible#309]
Please add widgets or buttons in notification. It won't be a big notification with basic functionality buttons such as start, stop and reset. Or at least a setting for users who prefer notification with buttons. Using tiles takes longer than going to the application from the notification. Widgets would also be useful, thanks

**Comment by Gedsh** [comment]
The latest beta version has a stop button in the notification. So the next stable version will have it as well. I don't know what the reset button is supposed to do, but there can't be a single start button since InviZible contains Tor, DNSCrypt, I2P and a firewall. I don't plan to add five buttons to the notification. That looks inconvenient to me. Anyway, thanks for the suggestion!

**Comment by Gedsh** [comment]
> Start button can do the same thing that the application does when you tap on the big start button

But in the case of notification, you won't be able to see which modules are starting and this can lead to an undesirable result.

> Reset button would just stop and restart the modules

How often do you use such restarts and for what purpose?

**Comment by Gedsh** [comment]
> why would we need to see the progress when we already know our settings?

You might have a good memory, but other people can make mistakes. Also the module may not start due to wrong configuration, new version or something else. In my opinion, it's better to see the process as it doesn't take as long.

> if mobile data is weak or there are network fluctuations, the app gets stuck on connecting.

In such cases, you should definitely see the interface to take the appropriate action rather than just pressing the restart button in the notification.

I got your point, but I don't like your idea. Sorry.

**Comment by Gedsh** [comment]
I prefer to keep a sane number of options, so I add new ones with great caution. This is not that case.
