### ISSUE TITLE
Tab: Snowflake

### ISSUE THREAD

**Issue by Zig-VS-TypeScript-VS** [Gedsh/InviZible#326]
Snowflake access on our InviZible

Allow users in censored countries to use your network connection to access the Tor network.

Help people in censored countries bypass censorship by running Snowflake If you want to help censored countries gain unrestricted access to the Internet, consider enabling the Snowflake option. Once enabled, you don't need to do anything else

https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake-webext/-/blob/main/config.js

https://snowflake.torproject.org/
https://nos-oignons.net/Snowflake/

**Comment by Gedsh** [comment]
You can use snowflake bridges in InviZible to circumvent censorship https://github.com/Gedsh/InviZible/wiki/Using-default-Bridges

If you're asking to add the ability to help other snowflake users bypass censorship, I have no such plans. I think mobile devices are not suitable for this purpose, because when you switch off the screen they always go into a doze mode to save battery power. In that mode you can't help other snowflake users. Doze mode can be disabled. But the battery consumption will be enormous.

Anyway, you can use Orbot to help other snowflake users. They have implemented this feature. But I recommend using the snowflake extension for browsers on PC. It will be much more useful.
