### ISSUE TITLE
move dnscrypt fallback_resolver to tor dnsport

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [Gedsh/InviZible#36]
you bypass tor for first request. of resolvers sources fetching and resolver address resolution.

solution is change
dnscrypt.toml
`fallback_resolver = '9.9.9.9:53'`
to
`fallback_resolver = '127.0.0.1:5400'`

and

`ignore_system_dns = false`
to
```
## Never let dnscrypt-proxy try to use the system DNS settings;
## unconditionally use the fallback resolver.

ignore_system_dns = true
```

**Comment by Gedsh** [comment]
> solution is change
dnscrypt.toml
fallback_resolver = '9.9.9.9:53'
to
fallback_resolver = '127.0.0.1:5400'

Fine. And what should DNSCrypt do when we don't start Tor or when we have problems with Tor connection?

> ignore_system_dns = true

This option causes problems on some devices.

**Comment by xp499** [comment]
> you bypass tor for first request. of resolvers sources fetching and resolver address resolution.
> 
> solution is change
> dnscrypt.toml
> `fallback_resolver = '9.9.9.9:53'`
> to
> `fallback_resolver = '127.0.0.1:5400'`
> 
> and
> 
> `ignore_system_dns = false`
> to
> 
> ```
> ## Never let dnscrypt-proxy try to use the system DNS settings;
> ## unconditionally use the fallback resolver.
> 
> ignore_system_dns = true
> ```

That'd be a nice/interesting feature if you're trying to avoid using clearnet DNS at all cost.

> > solution is change
> > dnscrypt.toml
> > fallback_resolver = '9.9.9.9:53'
> > to
> > fallback_resolver = '127.0.0.1:5400'
> 
> Fine. And what should DNSCrypt do when we don't start Tor or when we have problems with Tor connection?
> 
> > ignore_system_dns = true
> 
> This option causes problems on some devices.

@Gedsh is right. This should be optional and not mandatory or as default. But anyways this is easily resolved with app controls that detect tor module's already running. Otherwise start Tor module until it's ready to go, detect it and then start automatically DNSCrypt based on this behaviour and with that configuration option.

Last two issues/features proposed by @4-FLOSS-Free-Libre-Open-Source-Software are smart.
Nice feature proposal/additions @4-FLOSS-Free-Libre-Open-Source-Software !! :D
Please @Gedsh take these features within a timeless roadmap for the app.
We're not pushing you to work harder than you already do.
