### ISSUE TITLE
incompatibility with firefox

### ISSUE THREAD

**Issue by reyis4402** [Gedsh/InviZible#50]
The application causes many sites not to be opened in the firefox application for the new android. Firefox always gives a security warning
http://yenisafak.com/
![Screenshot_20201029-142516449](https://user-images.githubusercontent.com/60405617/97562518-090bbe80-19e2-11eb-9884-cb0badb354ad.jpg)

**Comment by Gedsh** [comment]
Check Firefox settings. It works for me:
![IMG_20201031_002414](https://user-images.githubusercontent.com/48843569/97762499-694d4e00-1b11-11eb-9e10-d7efc615f7cb.jpg)
![IMG_20201031_002503](https://user-images.githubusercontent.com/48843569/97762506-71a58900-1b11-11eb-8ccf-e54c7da017b3.jpg)

**Comment by reyis4402** [comment]
Try again for a second or third time and again I cannot access the NTV news site from any browser, there are serious problems.

https://www.ntv.com.tr/

![Screenshot_20201125-213114_Kiwi_Browser](https://user-images.githubusercontent.com/60405617/100268214-f6d75e80-2f54-11eb-913e-e34f0af5d3c0.png)
![Screenshot_20201125-213057_Firefox_Nightly](https://user-images.githubusercontent.com/60405617/100268227-fb037c00-2f54-11eb-81c7-d11d08876bf4.png)

**Comment by Ilithy** [comment]
Hello ;
@reyis4402 : I think the problem is on your side, I also tested the sites you mentioned, everything is perfectly accessible, test made on:
Oneplus 6 A6000
Android 10
inviZible Pro 5.0.0 (ARM64) - VPN mode - with tor and I2P in operation.

Here are some screenshots

Screenshot of the InviZible Pro GUI:

![Screenshot_20201125-202833](https://user-images.githubusercontent.com/36798218/100274643-16738480-2f5f-11eb-9025-bd8d3ec36c75.jpg)


Test on the latest version of Opera:

![Screenshot_20201125-203459](https://user-images.githubusercontent.com/36798218/100274705-31de8f80-2f5f-11eb-876c-9442ce8e5c2f.jpg)

![Screenshot_20201125-202944__01](https://user-images.githubusercontent.com/36798218/100274741-40c54200-2f5f-11eb-93d6-f48426e449ea.jpg)


Test on the latest version of Firefox:

![Screenshot_20201125-203109](https://user-images.githubusercontent.com/36798218/100274780-4f135e00-2f5f-11eb-8fa8-eb065977e041.jpg)

![Screenshot_20201125-203122](https://user-images.githubusercontent.com/36798218/100274810-589cc600-2f5f-11eb-9344-e63a2f528d78.jpg)

Screenshot of the InviZible Pro notification:

![Screenshot_20201125-203506](https://user-images.githubusercontent.com/36798218/100274843-62262e00-2f5f-11eb-9327-08a82caf14c0.jpg)

It even works very well, it's impressive 😍.
