### ISSUE TITLE
DNS leaks

### ISSUE THREAD

**Issue by rse12345** [Gedsh/InviZible#71]
Hi, thanks for the great app. I'm using netguard+invizible pro on calyxOS. I don't seem to be able to prevent DNS leaks, so that the VPN DNS is always the one queried i.e. quad9. I have set up port forwarding in netguard as per the instructions. any ideas?

**Comment by rhclayto** [comment]
Same problem here when following the instructions at https://github.com/Gedsh/InviZible/wiki/InviZible-and-NetGuard-firewall This might be a NetGuard issue, however, because it seems that NetGuard (FDroid version) does not use the port forwards when the VPN DNS servers are set. In addition to DNS leak tests showing the DNS serves configured for the NetGuard VPN (changing to 1.1.1.1 shows Cloudflare, etc.), also onion sites cannot be resolved, telling me that InviZible's dnscrypt-proxy is never seeing the requests.

If you leave the NetGuard VPN DNS entries blank, onion sites work & DNS leak tests show the DNSCrypt server being used.

**Comment by Gedsh** [comment]
@rse12345 @rhclayto Are there any leaks when using InviZible without NetGuard? Are you doing the test correctly according to the guide https://invizible.net/en/how-to-check-the-app/?

**Comment by rhclayto** [comment]
I find no leaks when using InviZible without NetGuard. I have followed the procedure from your how-to. To me it seems like a problem on the NetGuard side. When DNS servers are set for the NetGuard VPN, it seems to ignore the port forwards to 127.0.0.1:53: requests never show up in the InviZible Dnscrypt log, onion sites don't resolve, & the DNS servers set in the NetGuard VPN configuration show up in the leak tests while the DNSCrypt servers don't.

**Comment by Gedsh** [comment]
>  it seems to ignore the port forwards to 127.0.0.1:53

Why are you forwarding to this port? DNSCrypt listens on 5354 by default.

**Comment by rhclayto** [comment]
I'm sorry, it was a typo. I was forwarding to 5354.

**Comment by Gedsh** [comment]
> it seems there was something wrong with NetGuard (F-Droid edition)

Try another version of NetGuard, for example from github.

**Comment by rhclayto** [comment]
> Try another version of NetGuard, for example from github.

I will try it & report back.

**Comment by Gedsh** [comment]
Currently I am not using NetGuard, and cannot know if this is due to newer versions of NetGuard or your device. If you have Always On VPN enabled and block connections without VPN, I don't know what else to recommend.

**Comment by rse12345** [comment]
I am able to replicate the same issue as @rhclayto. 

I'll post it in XDA developers (https://forum.xda-developers.com/t/app-6-0-netguard-no-root-firewall.3233012/page-622). 

I prefer to have Invizible&netguard working in combination (I like the firewall, filters+list of access attempts provided by netguard)

thanks again for the great app

**Comment by Gedsh** [comment]
> thanks again for the great app

You are welcome!

**Comment by Gedsh** [comment]
Since InviZible does not redirect internet traffic in proxy mode, this issue cannot be related to InviZible. And I am not a NetGuard developer. So I close this issue.
