### ISSUE TITLE
Question about Tor restart

### ISSUE THREAD

**Issue by Yquas** [Gedsh/InviZible#91]
Before Beta v1.3.1, using the new Tor identity button was different. Now it's:
_Always use a full Tor restart when pressing the new identity button, which previously only happened with Tor bridges._ 
So what did InviZible do before? Why did you remove it? I am sure the new way is better and more secure. But it takes more time, even tho not much. Things have to re-login. Would you, @Gedsh, add the old way by a setting or something, or can you explain why it's bad and not coming back?

**Comment by Gedsh** [comment]
> So what did InviZible do before?

Previously InviZible would send SIGHUP signal to Tor to change the identity for new circuits, but existing circuits keep the connection and therefore the IP.

> Why did you remove it? 

By default, Tor automatically changes the IP for new circuits every 30 seconds. I think if someone wants to change the IP manually, it needs to be changed for all circuits, not just new ones. Since I don't see the point in doing it manually, as Tor does it automatically every 30 seconds. This parameter can be changed.

> Would you, @Gedsh, add the old way by a setting or something

Only if you explain why you need the old way.

**Comment by Yquas** [comment]
@Gedsh Ok, thanks for the explanation. If Tor changes the identity every 30 seconds already without one having to do anything, it's ok. Then there's no peoblem with the current implementation.
